### ISSUE TITLE
Adwords CSV generator

### ISSUE THREAD

**Issue by thijsc** [appsignal/marketing-tools#1]
The adwords interface doesn't make keeping a proper structure easy. Also we need to add UTM params to the url, which it does not do out of the box anymore.

We can solve this by writing a simple generator script that generates the relevant adwords-compatible CSV files we can then upload:

```yaml
---

ruby-exact: # Campaign
  ruby-on-rails: # Ad group
    keywords:
      -
        text: rails performance
        match: exact
        max_cpc: 1.20
    ads:
      -
        title: Rails Performance Tool
        line_1: Gain new insights Rails Performance
        line_2: Start your 30 day Free trial Now.
        line_3: Appsignal.com/Rails-Performance

# Results in this url:
# https://appsignal.com/for/ruby-on-rails?utm_source=adwords&utm_medium=cpc&utm_campaign=ruby-exact&utm_content=rails_performance_tool
#
# TODO: How about site extensions?
```
